README.md
Rakefile

Currently, classes that have since been removed or combined (like [MaximumMacOSRequirement](https://rubydoc.brew.sh/MaximumMacOSRequirement.html)) still appear in the API docs. This has the default `rake` task clear all but the `_config.yml` and `CNAME` files from `docs/` beforehand to remove any such stale files.
Also includes fixes for the README, one of which depends on Homebrew/brew#6418.
(cc @MikeMcQuaid)

Clear contents of docs/ before regenerating

---

.github/workflows/tests.yml

CI was passing because there was [nothing being built](https://github.com/Homebrew/rubydoc.brew.sh/runs/213231002#step:5:1).
(cc @MikeMcQuaid)

workflows/tests: clone Homebrew/brew before building

---

.github/workflows/scheduled.yml
Gemfile.lock

This mirrors what Homebrew/formulae.brew.sh does and allows the removal of the push job from Homebrew/brew.

Add scheduled regeneration CI jobs

---

.github/workflows/scheduled.yml

Needed to be able to commit.
Also, run every hour because the no-op case doesn't take too long.

workflows/scheduled: set git config.

---

.github/workflows/scheduled.yml
.github/workflows/tests.yml

- reset to `origin/master` to avoid pushing changes we're testing on the `scheduled.yml` job
- more closely match `tests.yml` and `scheduled.yml`

GitHub Actions (more) cleanup

---

.yardopts
README.md
ignore_directives.rb

Several items at https://rubydoc.brew.sh/ are missing their Overview section (e.g. [Formula](https://rubydoc.brew.sh/Formula.html); compare with an earlier version at [rubydoc.info](https://rubydoc.info/github/Homebrew/brew/Formula)) because the comments above the class extension in `extend/os/mac/formula.rb` or `extend/os/mac/formula.rb` are overwriting it. This is fixed by [reading the files in `extend/` first](https://stackoverflow.com/a/10344776). This also fixes private classes appearing that should be omitted from in the output, e.g. DevelopmentTools.
Other cases where the Overview is set to `typed: false\n frozen_string_literal: true` were resolved by using a [custom parser](https://github.com/lsegal/yard/issues/484#issuecomment-442586899) to remove the directives beforehand.
cc …

Avoid generating incorrect module/class overviews

---

.yardopts
ignore_directives.rb

Drop any comments that start with `typed:` or contain [`rubocop:`](https://rubydoc.brew.sh/Utils/Inreplace.html), and trim any comments containing `TODO:`.
cc @MikeMcQuaid

Refinements for ignored directives

---

Gemfile
Gemfile.lock
Rakefile

This will reduce duplication between the documentation and the type signatures, as we'll no longer need to add types to `@param` and `@return` for documented functions. For functions currently without documentation, this will at least add return types and such for functions that have been annotated with type signatures.

Use Sorbet type annotations for documentation.

---

.github/workflows/scheduled.yml
.github/workflows/tests.yml

Ruby 2.6 has reached EOL and the next release of `yard-sorbet` requires ruby >= 2.7.
(I tested that `bundle exec rake yard build` succeeds, lmk if there's anything else required)

Bump ruby version used in GH Actions

---

.github/workflows/scheduled.yml
.github/workflows/tests.yml

Starting with rubydoc.brew.sh.
`github-pages` gem support status is a little unclear now that Actions-based deploys are a thing. It does not support Ruby 3.2 and 3.x support in general is unclear. I think 3.1 might be ok?
Will need to be at least 3.1 as it will be parsing Homebrew/brew code, which will eventually be targetting a minimum of Ruby 3.1.

workflows: try use Ruby 3.1

---

.github/workflows/scheduled.yml
.github/workflows/tests.yml

Pin the version of the `setup-ruby` action to full length commit SHA as described in the [security hardening for GitHub Actions guide](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions).

workflows: pin setup-ruby action

---

Gemfile

We use `--markup markdown` but don't have `redcarpet` specified as a dependency, meaning docs are not actually being generated using Markdown, or at least not Github Flavored Markdown.

Add `redcarpet` gem for Markdown support.

---

Rakefile

These are now specified in [.yardopts](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/.yardopts).

Rakefile: remove redundant options

---

Gemfile
README.md

This is needed for `jekyll serve`. Also add note on using `yard server --reload`, which is useful for on-the-fly previewing of changes.

Gemfile: add webrick

---

.github/workflows/scheduled.yml
.github/workflows/stale-issues.yml
.github/workflows/tests.yml

Pin the version of the actions to full length commit SHA as described in the [security hardening for GitHub Actions guide](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions).

workflows: pin actions

---

.github/workflows/scheduled.yml

This should be the last PR of its kind.
This was added in Homebrew/actions#588. It simplifies the workflow, and reduces the number of API calls.
See also: Homebrew/formulae.brew.sh@f444253e2a99c0b3d021dbf7e7b0fefbce4e9d3c.

workflows/scheduled: use `create-or-update-issue` action

---

.github/workflows/scheduled.yml

Fixes failure seen at https://github.com/Homebrew/rubydoc.brew.sh/actions/runs/11016767778/job/30593186484.

workflows/scheduled: use `github.token`

---

.github/workflows/scheduled.yml
.github/workflows/tests.yml

This helps with transparency and they get updated by Dependabot.

workflows: use full version numbers

---

.github/workflows/scheduled.yml
.github/workflows/tests.yml

We don't need persistent credentials here.

workflows: fix artipacked zizmor findings

---

README.md
_config.yml

Allows `bundle exec jekyll serve` to work again after #775.

Ignore `brew` symlink in Jekyll config
